// scripts/set-env.js
const fs = require('fs-extra'); // Using fs-extra for mkdirp
const path = require('path');

const apiKey = process.env.API_KEY;
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!apiKey) {
  console.warn(
    'Warning: API_KEY for Gemini is not set in the build environment. Nutri-Kick AI will likely fail to connect to the Gemini API.'
  );
}
if (!supabaseUrl) {
  console.warn(
    'Warning: SUPABASE_URL is not set in the build environment. The application will not be able to connect to Supabase.'
  );
}
if (!supabaseAnonKey) {
  console.warn(
    'Warning: SUPABASE_ANON_KEY is not set in the build environment. The application will not be able to connect to Supabase.'
  );
}

const envConfigFileContent = `
// This file is generated by scripts/set-env.js during the build process.
// It makes environment variables available to the client-side application.
window.process = window.process || {};
window.process.env = window.process.env || {};
window.process.env.API_KEY = "${apiKey || 'MISSING_API_KEY_FROM_BUILD'}";
window.process.env.SUPABASE_URL = "${supabaseUrl || 'MISSING_SUPABASE_URL_FROM_BUILD'}";
window.process.env.SUPABASE_ANON_KEY = "${supabaseAnonKey || 'MISSING_SUPABASE_ANON_KEY_FROM_BUILD'}";
`;

// Output to the root directory, so index.html can easily find it via ./env-config.js
const outputPath = path.join(__dirname, '..', 'env-config.js');

try {
  fs.ensureDirSync(path.dirname(outputPath)); // Ensure directory exists
  fs.writeFileSync(outputPath, envConfigFileContent);
  console.log(`Environment configuration has been written to ${outputPath}`);
} catch (error) {
  console.error(`Error writing env-config.js: ${error}`);
  process.exit(1); // Exit with error code if script fails
}
